### ISSUE TITLE
PDO error (test at p.133 just prior to "Third Push"

### ISSUE THREAD

**Issue by twelch555** [spbooks/phpenv1-example#1]
Hi, working through the example chapter and encountered the following:

( ! ) Fatal error: Uncaught exception 'Exception' with message 'could not find driver' in C:\Users\twelch\hi_guestapp\guestbook\vendor\catfan\medoo\medoo.php on line 150
( ! ) Exception: could not find driver in C:\Users\twelch\hi_guestapp\guestbook\vendor\catfan\medoo\medoo.php on line 150
Call Stack
# Time    Memory  Function    Location

1   0.0066  138280  {main}( )   ...\index.php:0
2   0.0255  367104  medoo->__construct( )   ...\index.php:7

I'm going to do a careful comb through and make sure that my code entry is sound.

If there are no errors there I'll pull the files off the repo and test them against my environment.

If that yields no fruit I'll start digging into environment setup and see where the problem lies.

Just to be clear, I don't expect to have my problems solved for me, that's where the learning is. But when I figure out the issue I'll let you know, in case others run into the same issue.

Excellent book, I devoured it from front to back and will be recommending it widely.

Cheers

**Comment by twelch555** [comment]
Okay, sorted this out in quick order. I was using the "Open in Browser" command out of phpstorm rather than the url setup in hosts file.

**Comment by Swader** [comment]
Glad you got it to work :)
